version: '3.9'
services:
    es:
        image: elasticsearch:7.13.3
        ports:
            - 9200:9200
            - 9300:9300
        environment:
            - node.name=es01
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
        ulimits:
            memlock:
                soft: -1
                hard: -1

    hq:
        image: elastichq/elasticsearch-hq
        ports:
            - 5000:5000
        depends_on:
            - es